### ISSUE TITLE
warの作成の仕方について

### ISSUE THREAD

**Issue by wanomichi** [nabedge/mixer2-spboot14-sample#2]
いつもお世話になっております。
じまと申します。

サンプルアプリケーションをwarにしてtomcat環境にビルドをしたいのですが、どのようにすればよいでしょうか？
当方で変更した内容はpom.xmlのパッケージングをwarに変更し、【実行】->【Maven buird】->【ゴール】に
packageを記述して実行しましたが、targetフォルダにwarが生成されませんでした。

基本的なことで申し訳ありませんが、ご回答宜しくお願い致します。

**Comment by nabedge** [comment]
こちらが参考になるのと思います。
- https://spring.io/guides/gs/convert-jar-to-war/
- http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-maven-packaging

**Comment by wanomichi** [comment]
warを作ってデプロイするというのは時代遅れ（？）なのですね・・・

組み込みtomcatの起動で対応したいと思います。
勉強になりました。
ありがとうございます。
